# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f7807441b52ef268a7f0b20fcfd71f0351622c0f4e58e62e2d8b12c6c3200a7a428d920f183ef88bf554df5e4d3583634fafa5a49cd9d6c31a7e5f2de7e799a

test:
  secret_key_base: c42d37a8ced59d33a5751c60787b06abdc47978778a6da4a14e784a5f98055c303b2eb176f9d51fc5659c0f7523e015d123c39fff8fc004550b7907ab97671c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
